### ISSUE TITLE
Installation: incompatible character encodings error

### ISSUE THREAD

**Issue by xywang68** [criteo/vagrant-winrm#13]
Env:
Windows7 x64 (US-English)
Vagrant version 1.9.5

Issue:
Installation failed for Ruby Encoding::CompatibilityError

Log:
$ vagrant plugin install vagrant-winrm-0.7.0.gem
Installing the 'vagrant-winrm-0.7.0.gem' plugin. This can take a few minutes...
C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/resolv.rb:769:in `[]=': incompatible character encodings: UTF-8 and ASCII-8BIT (Encoding::CompatibilityError)
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/resolv.rb:769:in `sender'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/resolv.rb:524:in `block in fetch_resource'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/resolv.rb:1096:in `block (3 levels) in resolv'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/resolv.rb:1094:in `each'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/resolv.rb:1094:in `block (2 levels) in resolv'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/resolv.rb:1093:in `each'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/resolv.rb:1093:in `block in resolv'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/resolv.rb:1091:in `each'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/resolv.rb:1091:in `resolv'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/resolv.rb:519:in `fetch_resource'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/resolv.rb:509:in `each_resource'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/resolv.rb:490:in `getresource'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/rubygems/remote_fetcher.rb:92:in `api_endpoint'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/rubygems/source.rb:46:in `api_uri'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/rubygems/source.rb:138:in `fetch_spec'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/rubygems/resolver/api_specification.rb:76:in `spec'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/rubygems/resolver/activation_request.rb:74:in `full_spec'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.5/lib/vagrant/bundler.rb:386:in `block in activate_solution'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.5/lib/vagrant/bundler.rb:385:in `each'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.5/lib/vagrant/bundler.rb:385:in `activate_solution'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.5/lib/vagrant/bundler.rb:288:in `internal_install'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.5/lib/vagrant/bundler.rb:123:in `install_local'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.5/lib/vagrant/plugin/manager.rb:47:in `install_plugin'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.5/plugins/commands/plugin/action/install_gem.rb:29:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.5/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.5/lib/vagrant/action/builder.rb:116:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.5/lib/vagrant/action/runner.rb:66:in `block in run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.5/lib/vagrant/util/busy.rb:19:in `busy'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.5/lib/vagrant/action/runner.rb:66:in `run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.5/plugins/commands/plugin/command/base.rb:14:in `action'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.5/plugins/commands/plugin/command/install.rb:32:in `block in execute'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.5/plugins/commands/plugin/command/install.rb:31:in `each'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.5/plugins/commands/plugin/command/install.rb:31:in `execute'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.5/plugins/commands/plugin/command/root.rb:66:in `execute'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.5/lib/vagrant/cli.rb:42:in `execute'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.5/lib/vagrant/environment.rb:308:in `cli'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.5/bin/vagrant:138:in `<main>'

**Comment by joffreypannequin** [comment]
I encoutered the same issue. This seems to happen only with some network/DNS configuration.

The following workaround worked for me: https://gist.github.com/tygerbytes/f40735f107a28be4897e669b61a0117b

**Edit resolv.rb. Replace (i did it in several places not just the line mentioned in the gist):** 
```rb
          request[0,2] = [id].pack('n')
```
by 
```rb
          request[0,2] = [id].pack('U')
```

**Comment by kamaradclimber** [comment]
Thanks for the info @joffreypannequin . It means this is a very specific issue to ruby on windows.
I'll close that issue since there is nothing thatt this project can do to solev it.
