### ISSUE TITLE
Running a blocking command prevents further use of winrm

### ISSUE THREAD

**Issue by cwc** [criteo/vagrant-winrm#9]
Haven't looked at the code, so I'm not sure if running a command that requires input is even meant to be supported. In any case, to repro: 

* Run a blocking command, e.g. 'choco install jdk8'
* Verify that input is ignored/doesn't affect the VM
* Hit ^C to kill the winrm plugin
* Try another winrm command
* Verify that winrm connects and displays the output from the *previous* command

**Comment by Annih** [comment]
Hello @cwc 

Sorr for the delay, but yeah blocking command are not supported.

Regards.
